[pytest]
norecuresedirs = .git
python_files = test_*.py tests.py
testpaths =
  jsearch/api/tests
  jsearch/common/tests
  jsearch/data_checker/tests
  jsearch/pending_syncer/tests
  jsearch/syncer/tests
  jsearch/tests
; Doctests:
  jsearch/utils.py
  jsearch/common/wallet_events.py
  jsearch/syncer/pool.py
  jsearch/api/serializers/common.py
addopts =
  -vv
  --cov=jsearch
  --cov-fail-under=75
  --cov-config .coveragerc
  --doctest-modules
filterwarnings =
  ; https://github.com/cr0hn/aiohttp-swagger/issues/60
  ignore::yaml.YAMLLoadWarning:.*aiohttp_swagger.*:123

  ; https://github.com/aio-libs/aiopg/issues/508
  ignore::DeprecationWarning:.*aiopg.*:46
  ignore::DeprecationWarning:.*aiopg.*:170
  ignore::DeprecationWarning:.*aiopg.*:235
  ignore::DeprecationWarning:.*aiopg.*:155

  ; `pytest` complains that `aiohttp.test_utils.TestClient` is called like a
  ; test but has `__init__` method.
  ignore::_pytest.warning_types.PytestCollectionWarning:.*aiohttp.*:226
